// This file is auto-generated by @hey-api/openapi-ts

export type RegisterDto = {
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Имя пользователя
     */
    firstName: string;
    /**
     * Фамилия пользователя
     */
    lastName: string;
    /**
     * Пароль пользователя (минимум 6 символов)
     */
    password: string;
    /**
     * Отчество пользователя
     */
    patronymic?: string;
    /**
     * Роль пользователя
     */
    role: 'TUTOR' | 'STUDENT';
};

export type ResponseStudentProfileDto = {
    /**
     * Класс студента
     */
    grade?: number;
    /**
     * Уникальный идентификатор профиля студента
     */
    id: string;
};

export type ResponseTutorProfileDto = {
    /**
     * Описание репетитора
     */
    description?: string;
    /**
     * Опыт работы в годах
     */
    experience?: number;
    /**
     * Почасовая ставка
     */
    hourlyRate?: number;
    /**
     * Уникальный идентификатор профиля репетитора
     */
    id: string;
    /**
     * Рейтинг репетитора
     */
    rating?: number;
    /**
     * Предметы, которые преподает репетитор
     */
    subjects: Array<string>;
};

export type ResponseUserDto = {
    /**
     * Дата создания пользователя
     */
    createdAt: string;
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Имя пользователя
     */
    firstName: string;
    /**
     * Уникальный идентификатор пользователя
     */
    id: string;
    /**
     * Фамилия пользователя
     */
    lastName: string;
    /**
     * Отчество пользователя
     */
    patronymic?: string;
    /**
     * Роль пользователя
     */
    role: 'TUTOR' | 'STUDENT';
    /**
     * Профиль студента
     */
    student?: ResponseStudentProfileDto;
    /**
     * Профиль репетитора
     */
    tutor?: ResponseTutorProfileDto;
    /**
     * Дата последнего обновления пользователя
     */
    updatedAt: string;
};

export type SignInDto = {
    /**
     * Email пользователя
     */
    email: string;
    /**
     * Пароль пользователя
     */
    password: string;
};

export type SubscriptionPlanDto = {
    /**
     * Описание плана подписки
     */
    description?: string;
    /**
     * Продолжительность плана в днях
     */
    duration: number;
    /**
     * Список функций плана подписки
     */
    features: Array<string>;
    /**
     * ID плана подписки
     */
    id: string;
    /**
     * Флаг активности плана подписки
     */
    isActive: boolean;
    /**
     * Флаг пробного плана подписки
     */
    isTrial: boolean;
    /**
     * Название плана подписки
     */
    name: string;
    /**
     * Стоимость плана подписки
     */
    price: number;
};

export type SubscriptionDto = {
    /**
     * Флаг автопродления подписки
     */
    autoRenew: boolean;
    /**
     * Дата окончания подписки
     */
    endDate: string;
    /**
     * ID подписки
     */
    id: string;
    /**
     * План подписки
     */
    plan: SubscriptionPlanDto;
    /**
     * Дата начала подписки
     */
    startDate: string;
    /**
     * Статус подписки
     */
    status: 'ACTIVE' | 'CANCELLED' | 'EXPIRED' | 'PAUSED';
    /**
     * ID преподавателя
     */
    tutorId: string;
};

export type TrialStatusResponseDto = {
    /**
     * Количество оставшихся дней пробной подписки
     */
    daysLeft: number;
    /**
     * Флаг наличия пробной подписки
     */
    hasTrial: boolean;
    /**
     * Флаг истечения пробной подписки
     */
    isExpired?: boolean;
    /**
     * Статус пробной подписки
     */
    status?: 'ACTIVE' | 'CANCELLED' | 'EXPIRED' | 'PAUSED';
    /**
     * Информация о подписке
     */
    subscription?: SubscriptionDto;
};

export type UpgradeSubscriptionDto = {
    /**
     * ID плана подписки для обновления
     */
    planId: string;
};

export type AppControllerGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerGetHealthResponses = {
    /**
     * Server is running
     */
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type AuthControllerRegisterErrors = {
    /**
     * Invalid registration data
     */
    400: unknown;
    /**
     * User with this email already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * User successfully registered
     */
    201: ResponseUserDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerSignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type AuthControllerSignInErrors = {
    /**
     * Invalid email or password
     */
    401: unknown;
};

export type AuthControllerSignInResponses = {
    /**
     * Successfully authenticated
     */
    200: ResponseUserDto;
};

export type AuthControllerSignInResponse = AuthControllerSignInResponses[keyof AuthControllerSignInResponses];

export type AuthControllerSignOutData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/auth/sign-out';
};

export type AuthControllerSignOutResponses = {
    200: unknown;
};

export type SubscriptionControllerCheckTrialStatusData = {
    body?: never;
    path: {
        tutorId: string;
    };
    query?: never;
    url: '/subscriptions/tutor/{tutorId}/trial-status';
};

export type SubscriptionControllerCheckTrialStatusResponses = {
    /**
     * Информация о пробной подписке успешно получена
     */
    200: TrialStatusResponseDto;
};

export type SubscriptionControllerCheckTrialStatusResponse = SubscriptionControllerCheckTrialStatusResponses[keyof SubscriptionControllerCheckTrialStatusResponses];

export type SubscriptionControllerGetActiveSubscriptionData = {
    body?: never;
    path: {
        tutorId: string;
    };
    query?: never;
    url: '/subscriptions/tutor/{tutorId}/active';
};

export type SubscriptionControllerGetActiveSubscriptionResponses = {
    /**
     * Информация об активной подписке успешно получена
     */
    200: SubscriptionDto;
};

export type SubscriptionControllerGetActiveSubscriptionResponse = SubscriptionControllerGetActiveSubscriptionResponses[keyof SubscriptionControllerGetActiveSubscriptionResponses];

export type SubscriptionControllerUpgradeToPaidSubscriptionData = {
    body: UpgradeSubscriptionDto;
    path: {
        subscriptionId: string;
    };
    query?: never;
    url: '/subscriptions/upgrade/{subscriptionId}';
};

export type SubscriptionControllerUpgradeToPaidSubscriptionErrors = {
    /**
     * Подписка или план не найдены
     */
    400: unknown;
};

export type SubscriptionControllerUpgradeToPaidSubscriptionResponses = {
    /**
     * Подписка успешно обновлена
     */
    200: SubscriptionDto;
};

export type SubscriptionControllerUpgradeToPaidSubscriptionResponse = SubscriptionControllerUpgradeToPaidSubscriptionResponses[keyof SubscriptionControllerUpgradeToPaidSubscriptionResponses];

export type ClientOptions = {
    baseUrl: string;
};